"""Constants for admin sales management module."""

# Product status constants for dashboard filtering
PRODUCT_STATUS_SELLING = "SELLING"
PRODUCT_STATUS_SELLING_DONATION_PHASE = "SELLING_DONATION_PHASE"
PRODUCT_STATUS_SOLD_DONATION = "SOLD_DONATION"
PRODUCT_STATUS_SOLD_PICKED_UP = "SOLD_PICKED_UP"
PRODUCT_STATUS_SOLD_READY_FOR_PICK_UP = "SOLD_READY_FOR_PICK_UP"
PRODUCT_STATUS_EXPIRED = "EXPIRED"

# Valid product status values
VALID_PRODUCT_STATUSES = {
    PRODUCT_STATUS_SELLING,
    PRODUCT_STATUS_SELLING_DONATION_PHASE,
    PRODUCT_STATUS_SOLD_DONATION,
    PRODUCT_STATUS_SOLD_PICKED_UP,
    PRODUCT_STATUS_SOLD_READY_FOR_PICK_UP,
    PRODUCT_STATUS_EXPIRED,
}
