FIRST_HALF_THIS_YEAR = "FIRST_HALF_THIS_YEAR"
SECOND_HALF_THIS_YEAR = "SECOND_HALF_THIS_YEAR"
FIRST_HALF_LAST_YEAR = "FIRST_HALF_LAST_YEAR"
SECOND_HALF_LAST_YEAR = "SECOND_HALF_LAST_YEAR"
SECOND_HALF_YEAR_BEFORE_LAST = "SECOND_HALF_YEAR_BEFORE_LAST"
QUARTERS_THIS_YEAR = "QUARTERS_THIS_YEAR"
MONTHS_THIS_YEAR = "MONTHS_THIS_YEAR"
WEEKS_THIS_MONTH = "WEEKS_THIS_MONTH"
TODAY = "TODAY"

TIME_DURATION_FILTER = {
    FIRST_HALF_THIS_YEAR,
    SECOND_HALF_THIS_YEAR,
    FIRST_HALF_LAST_YEAR,
    SECOND_HALF_LAST_YEAR,
    SECOND_HALF_YEAR_BEFORE_LAST,
    QUARTERS_THIS_YEAR,
    MONTHS_THIS_YEAR,
    WEEKS_THIS_MONTH,
    TODAY,
}

# User retention specific durations
THIS_QUARTER = "THIS_QUARTER"
THIS_MONTH = "THIS_MONTH"
THIS_WEEK = "THIS_WEEK"

USER_RETENTION_DURATION_FILTER = {
    FIRST_HALF_THIS_YEAR,
    SECOND_HALF_THIS_YEAR,
    THIS_QUARTER,
    THIS_MONTH,
    THIS_WEEK,
    TODAY,
}

TIME_DURATION_INVALID = "Invalid time duration. Please select a valid period"
TOTAL_MISMATCH_ERROR = "Total revenue does not match the sum of monthly revenues"
INVALID_TIME_DURATION = "Invalid time duration. Please select a valid period"

# User statistics metrics
METRIC_CUSTOMER_COUNT = "CUSTOMER_COUNT"
METRIC_REVENUE = "REVENUE"
VALID_METRICS = [METRIC_CUSTOMER_COUNT, METRIC_REVENUE]

# User retention segments
SEGMENT_ONE_TIME = "ONE_TIME"
SEGMENT_RETURNING = "RETURNING"
VALID_SEGMENTS = [SEGMENT_ONE_TIME, SEGMENT_RETURNING]
