from .config import API_PREFIX

ALLOWED_GLOBAL_UNAUTHENTICATED_PATHS = {
    "/health": "GET",
    "/docs": "GET",
    "/redoc": "GET",
    "/openapi.json": "GET",
}

# Exact path match (method: path)
ALLOWED_UNAUTHENTICATED_PATHS = {
    "/auth/token": "POST",
    "/auth/register": "POST",
    "/auth/refresh": "POST",
}

# Prefix match: any path starting with these prefixes + method is allowed without auth
ALLOWED_UNAUTHENTICATED_PREFIXES = [
    ("/combos", "GET"),
    ("/shops", "GET"),
    ("/lockers", "GET"),
    ("/reviews", "GET"),
    ("/uploads/", "GET"),
]

EXCLUDED_FROM_WILDCARD_PATTERNS = {}

# ── Combo Status Constants ──
# DRAFT -> PREPARATION_TO_LOCKER -> SELLING -> SOLD
#                                |-> EXPIRED (listing timeout, no buyer)
#                    |-> EXPIRED_PUT_IN_LOCKER (staff didn't place in time)
# Any status -> DELETED (shop cancels combo, soft-delete)
COMBO_STATUS_DRAFT = "DRAFT"
COMBO_STATUS_PREPARATION_TO_LOCKER = "PREPARATION_TO_LOCKER"
COMBO_STATUS_EXPIRED_PUT_IN_LOCKER = "EXPIRED_PUT_IN_LOCKER"
COMBO_STATUS_SELLING = "SELLING"
COMBO_STATUS_SOLD = "SOLD"
COMBO_STATUS_EXPIRED = "EXPIRED"
COMBO_STATUS_DELETED = "DELETED"

# ── Order Status Constants ──
ORDER_STATUS_PENDING_PAYMENT = "PENDING_PAYMENT"
ORDER_STATUS_READY_FOR_PICKUP = "READY_FOR_PICKUP"
ORDER_STATUS_PICKED_UP = "PICKED_UP"
ORDER_STATUS_REFUNDED = "REFUNDED"

# ── Payment Status Constants ──
PAYMENT_INIT = "INIT"
PAYMENT_UNPROCESSED = "UNPROCESSED"
PAYMENT_CAPTURED = "CAPTURED"
PAYMENT_FAILED = "FAILED"

PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_COMPLETED = "COMPLETED"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_REFUNDED = "REFUNDED"

# ── Locker Unit Status ──
UNIT_STATUS_AVAILABLE = "AVAILABLE"
UNIT_STATUS_RESERVED = "RESERVED"
UNIT_STATUS_OCCUPIED = "OCCUPIED"
UNIT_STATUS_MAINTENANCE = "MAINTENANCE"

# ── Reservation Status ──
RESERVATION_STATUS_PENDING = "PENDING"
RESERVATION_STATUS_ACTIVE = "ACTIVE"
RESERVATION_STATUS_COMPLETED = "COMPLETED"
RESERVATION_STATUS_CANCELLED = "CANCELLED"

# ── Combo Purchasable / Updatable / Deletable lists ──
COMBO_PURCHASABLE_STATUSES = [COMBO_STATUS_SELLING]
COMBO_DELETABLE_STATUSES = [COMBO_STATUS_DRAFT, COMBO_STATUS_EXPIRED, COMBO_STATUS_DELETED]
COMBO_UPDATABLE_STATUSES = [COMBO_STATUS_DRAFT, COMBO_STATUS_SELLING]

# ── Time-based thresholds ──
COMBO_SALE_TIME_HOURS = 8
