from enum import Enum


class NotificationType(str, Enum):
    # Buyer notifications (based on documentation)
    COMBO_PICKUP_DEADLINE_PASSED = "COMBO_PICKUP_DEADLINE_PASSED"
    COMBO_EXPIRED_SALES = "COMBO_EXPIRED_SALES"
    NEW_COMBO_FROM_FAVORITE_STORE = "NEW_COMBO_FROM_FAVORITE_STORE"
    COMBO_PICKUP_DEADLINE_APPROACHING = "COMBO_PICKUP_DEADLINE_APPROACHING"
    ORDER_CANCELED = "ORDER_CANCELED"
    PRODUCT_EXPIRY_REACHED = "PRODUCT_EXPIRY_REACHED"

    # Store notifications (based on documentation)
    USER_BUY_COMBO = "USER_BUY_COMBO"
    USER_CANCELLED_COMBO = "USER_CANCELLED_COMBO"
    COMBO_PICKUP_COMPLETED = "COMBO_PICKUP_COMPLETED"
    PRODUCT_EXPIRED = "PRODUCT_EXPIRED"
    NEW_REVIEW_RECEIVED = "NEW_REVIEW_RECEIVED"
    COMBO_PLACEMENT_DEADLINE_APPROACHING = "COMBO_PLACEMENT_DEADLINE_APPROACHING"


class UserType(str, Enum):
    BUYER = "buyer"
    STORE = "store"


# Notification type constants
SYSTEM_BROADCAST = "SYSTEM_BROADCAST"
USER_TARGETED = "USER_TARGETED"
